apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://airbyte-abctl-control-plane:6443
    certificate-authority: /etc/kubernetes/pki/ca.crt
  name: airbyte-abctl-control-plane
contexts:
- context:
    cluster: airbyte-abctl-control-plane
    user: kubernetes-admin
  name: airbyte-abctl-control-plane
current-context: airbyte-abctl-control-plane
